// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeqNf9eUyc2EQjur85LVMeVZxuB5pRBTQ',
    appId: '1:621118810715:web:06c4d6c9a7c670e4016d7e',
    messagingSenderId: '621118810715',
    projectId: 'jatai-etat-des-lieux',
    authDomain: 'jatai-etat-des-lieux.firebaseapp.com',
    storageBucket: 'jatai-etat-des-lieux.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn6YE78JFZufu1TMiwhU-vjQpldaz2ta8',
    appId: '1:621118810715:android:84da68e13212fcfe016d7e',
    messagingSenderId: '621118810715',
    projectId: 'jatai-etat-des-lieux',
    storageBucket: 'jatai-etat-des-lieux.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0mwgxzWBb31PR049xqhJk4-8xP_AW7gE',
    appId: '1:621118810715:ios:685e4dacb1e77d4e016d7e',
    messagingSenderId: '621118810715',
    projectId: 'jatai-etat-des-lieux',
    storageBucket: 'jatai-etat-des-lieux.firebasestorage.app',
    iosBundleId: 'com.jatai.etatsdeslieux',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0mwgxzWBb31PR049xqhJk4-8xP_AW7gE',
    appId: '1:621118810715:ios:685e4dacb1e77d4e016d7e',
    messagingSenderId: '621118810715',
    projectId: 'jatai-etat-des-lieux',
    storageBucket: 'jatai-etat-des-lieux.firebasestorage.app',
    iosBundleId: 'com.jatai.etatsdeslieux',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeqNf9eUyc2EQjur85LVMeVZxuB5pRBTQ',
    appId: '1:621118810715:web:821e3128887f4029016d7e',
    messagingSenderId: '621118810715',
    projectId: 'jatai-etat-des-lieux',
    authDomain: 'jatai-etat-des-lieux.firebaseapp.com',
    storageBucket: 'jatai-etat-des-lieux.firebasestorage.app',
  );

}